
# Helper script — writes party_ui.gd
import os

code = (
    "# 260710 Red party_ui v2\n"
    "extends CanvasLayer\n"
    "signal closed\n"
    "\n"
    "const VW := 1280; const VH := 720\n"
    "const LEFT_W  := 300\n"
    "const CARD_H  := 96\n"
    "const CARD_GAP := 8\n"
    "const CARD_X  := 12\n"
    "const CARD_Y  := 56\n"
    "\n"
    "const C_BG          := Color(0.075, 0.102, 0.157)\n"
    "const C_LEFT        := Color(0.090, 0.118, 0.176)\n"
    "const C_CARD        := Color(0.114, 0.149, 0.220)\n"
    "const C_CARD_SEL    := Color(0.204, 0.369, 0.631)\n"
    "const C_CARD_BORDER := Color(0.200, 0.260, 0.380)\n"
    "const C_SEL_BORDER  := Color(0.388, 0.588, 0.929)\n"
    "const C_TEXT        := Color(0.878, 0.906, 0.953)\n"
    "const C_SUB         := Color(0.439, 0.533, 0.639)\n"
    "const C_ACCENT      := Color(0.388, 0.588, 0.929)\n"
    "const C_PANEL       := Color(0.102, 0.133, 0.196)\n"
    "const C_DIVIDER     := Color(0.176, 0.224, 0.314)\n"
    "const HP_G := Color(0.278, 0.808, 0.408)\n"
    "const HP_Y := Color(0.961, 0.780, 0.216)\n"
    "const HP_R := Color(0.918, 0.267, 0.267)\n"
    "\n"
    "const TYPE_COLORS := {\n"
    "\t\"\u706b\":Color(0.93,0.37,0.18),\"\u6c34\":Color(0.22,0.58,0.95),\"\u8349\":Color(0.28,0.75,0.32),\n"
    "\t\"\u6728\":Color(0.38,0.65,0.22),\"\u7535\":Color(0.96,0.82,0.15),\"\u51b0\":Color(0.38,0.82,0.90),\n"
    "\t\"\u683c\u6597\":Color(0.76,0.25,0.22),\"\u6bd2\":Color(0.62,0.25,0.72),\"\u5730\u9762\":Color(0.82,0.65,0.28),\n"
    "\t\"\u98de\u884c\":Color(0.55,0.65,0.90),\"\u8d85\u80fd\":Color(0.90,0.28,0.55),\"\u866b\":Color(0.62,0.72,0.12),\n"
    "\t\"\u5ca9\u77f3\":Color(0.60,0.52,0.28),\"\u5e7d\u7075\":Color(0.38,0.28,0.62),\"\u9f99\":Color(0.30,0.18,0.90),\n"
    "\t\"\u6076\":Color(0.28,0.20,0.15),\"\u9492\":Color(0.60,0.62,0.68),\"\u5996\u7cbe\":Color(0.92,0.58,0.72),\n"
    "\t\"\u5149\":Color(0.98,0.92,0.52),\"\u98ce\":Color(0.52,0.82,0.72),\"\u6b63\u5e38\":Color(0.68,0.68,0.62),\n"
    "}\n"
    "const STAT_COLORS := [\n"
    "\tColor(0.28,0.78,0.40), Color(0.92,0.35,0.28), Color(0.93,0.65,0.18),\n"
    "\tColor(0.32,0.55,0.92), Color(0.82,0.32,0.52), Color(0.28,0.72,0.88),\n"
    "]\n"
    "const STAT_KEYS  := [\"hp\",\"atk\",\"def\",\"sp_atk\",\"sp_def\",\"spd\"]\n"
    "const STAT_NAMES := [\"HP\",\"\u653b\u51fb\",\"\u9632\u5fa1\",\"\u7279\u653b\",\"\u7279\u9632\",\"\u901f\u5ea6\"]\n"
    "const ACTIONS    := [\"\u6392\u5e8f\",\"\u66ff\u6362\",\"\u8fd4\u56de\"]\n"
    "\n"
    "var _root: Control\n"
    "var _cursor: int = 0\n"
    "var _focus: String = \"party\"\n"
    "var _action_cursor: int = 0\n"
    "\n"
    "func _ready() -> void:\n"
    "\tlayer = 51\n"
    "\tprocess_mode = Node.PROCESS_MODE_ALWAYS\n"
    "\t_build_ui()\n"
    "\n"
    "func _build_ui() -> void:\n"
    "\t_root = Control.new()\n"
    "\t_root.set_anchors_preset(Control.PRESET_FULL_RECT)\n"
    "\tadd_child(_root)\n"
    "\t_render()\n"
    "\n"
    "func _render() -> void:\n"
    "\tfor c in _root.get_children(): c.queue_free()\n"
    "\tawait get_tree().process_frame\n"
    "\t_draw_bg()\n"
    "\t_draw_left()\n"
    "\t_draw_right()\n"
    "\t_draw_actions()\n"
    "\t_draw_close_btn()\n"
    "\n"
    "func _draw_bg() -> void:\n"
    "\tvar bg = ColorRect.new()\n"
    "\tbg.size = Vector2(VW, VH); bg.color = C_BG; _root.add_child(bg)\n"
    "\tvar left_bg = ColorRect.new()\n"
    "\tleft_bg.size = Vector2(LEFT_W, VH); left_bg.color = C_LEFT; _root.add_child(left_bg)\n"
    "\tvar div = ColorRect.new()\n"
    "\tdiv.size = Vector2(1, VH); div.position = Vector2(LEFT_W, 0)\n"
    "\tdiv.color = C_DIVIDER; _root.add_child(div)\n"
    "\n"
    "func _draw_left() -> void:\n"
    "\tvar title = Label.new()\n"
    "\ttitle.text = \"\u6211\u7684\u7cbe\u7075\"; title.position = Vector2(CARD_X + 6, 16)\n"
    "\ttitle.add_theme_font_size_override(\"font_size\", 20)\n"
    "\ttitle.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(title)\n"
    "\tvar team = GameState.player_team\n"
    "\tfor i in range(6):\n"
    "\t\tvar cy = CARD_Y + i * (CARD_H + CARD_GAP)\n"
    "\t\tif i < team.size(): _draw_card(i, team[i], cy)\n"
    "\t\telse: _draw_empty_card(cy)\n"
    "\n"
    "func _draw_card(idx: int, mon: Dictionary, cy: int) -> void:\n"
    "\tvar sel = (idx == _cursor and _focus == \"party\")\n"
    "\tvar sp = MonDB.species.get(mon.get(\"species_id\",\"\"), {})\n"
    "\tvar t1 = sp.get(\"type1\",\"\u6b63\u5e38\")\n"
    "\tvar tc = TYPE_COLORS.get(t1, C_ACCENT)\n"
    "\tvar cw = LEFT_W - CARD_X * 2\n"
    "\tvar panel = _make_panel(Vector2(CARD_X, cy), Vector2(cw, CARD_H),\n"
    "\t\tC_CARD_SEL if sel else C_CARD,\n"
    "\t\tC_SEL_BORDER if sel else C_CARD_BORDER, 12, 2 if sel else 1)\n"
    "\t_root.add_child(panel)\n"
    "\tvar stripe = ColorRect.new()\n"
    "\tstripe.size = Vector2(4, CARD_H - 16); stripe.position = Vector2(CARD_X + 6, cy + 8)\n"
    "\tstripe.color = tc; _root.add_child(stripe)\n"
    "\tvar icon_path = \"res://assets/sprites/%sfront.png\" % mon.get(\"species_id\",\"\")\n"
    "\tif ResourceLoader.exists(icon_path):\n"
    "\t\tvar icon = TextureRect.new(); icon.texture = load(icon_path)\n"
    "\t\ticon.expand_mode = TextureRect.EXPAND_IGNORE_SIZE\n"
    "\t\ticon.custom_minimum_size = Vector2(56, 56); icon.size = Vector2(56, 56)\n"
    "\t\ticon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED\n"
    "\t\ticon.position = Vector2(CARD_X + 14, cy + (CARD_H - 56) / 2)\n"
    "\t\t_root.add_child(icon)\n"
    "\tvar tx = CARD_X + 76\n"
    "\tvar gender = mon.get(\"gender\",\"\")\n"
    "\tvar glyph = \" \u2642\" if gender == \"male\" else \" \u2640\" if gender == \"female\" else \"\"\n"
    "\tvar nl = Label.new()\n"
    "\tnl.text = MonDB.display_name(mon) + glyph; nl.position = Vector2(tx, cy + 10)\n"
    "\tnl.add_theme_font_size_override(\"font_size\", 16)\n"
    "\tnl.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(nl)\n"
    "\tvar lv = Label.new()\n"
    "\tlv.text = \"Lv.%d\" % mon.get(\"level\",1)\n"
    "\tlv.position = Vector2(CARD_X + cw - 36, cy + 12)\n"
    "\tlv.add_theme_font_size_override(\"font_size\", 13)\n"
    "\tlv.add_theme_color_override(\"font_color\", tc if sel else C_SUB); _root.add_child(lv)\n"
    "\tvar hp_r = float(mon.get(\"current_hp\",0)) / max(float(mon.get(\"max_hp\",1)), 1.0)\n"
    "\tvar bw = cw - 80\n"
    "\tvar bar_bg = ColorRect.new()\n"
    "\tbar_bg.size = Vector2(bw, 8); bar_bg.position = Vector2(tx, cy + 38)\n"
    "\tbar_bg.color = Color(0.15, 0.19, 0.28); _root.add_child(bar_bg)\n"
    "\tvar bar = ColorRect.new()\n"
    "\tbar.size = Vector2(bw * hp_r, 8); bar.position = Vector2(tx, cy + 38)\n"
    "\tbar.color = HP_G if hp_r > 0.5 else HP_Y if hp_r > 0.2 else HP_R; _root.add_child(bar)\n"
    "\tvar hp_lbl = Label.new()\n"
    "\thp_lbl.text = \"%d / %d\" % [mon.get(\"current_hp\",0), mon.get(\"max_hp\",1)]\n"
    "\thp_lbl.position = Vector2(tx, cy + 52)\n"
    "\thp_lbl.add_theme_font_size_override(\"font_size\", 12)\n"
    "\thp_lbl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(hp_lbl)\n"
    "\n"
    "func _draw_empty_card(cy: int) -> void:\n"
    "\tvar cw = LEFT_W - CARD_X * 2\n"
    "\tvar panel = _make_panel(Vector2(CARD_X, cy), Vector2(cw, CARD_H),\n"
    "\t\tColor(C_CARD.r, C_CARD.g, C_CARD.b, 0.5), C_DIVIDER, 12, 1)\n"
    "\t_root.add_child(panel)\n"
    "\tvar lbl = Label.new(); lbl.text = \"\u2014 \u7a7a\u69fd \u2014\"\n"
    "\tlbl.position = Vector2(CARD_X + cw/2 - 28, cy + CARD_H/2 - 9)\n"
    "\tlbl.add_theme_font_size_override(\"font_size\", 13)\n"
    "\tlbl.add_theme_color_override(\"font_color\", C_DIVIDER); _root.add_child(lbl)\n"
    "\n"
    "func _draw_right() -> void:\n"
    "\tvar team = GameState.player_team\n"
    "\tif _cursor >= team.size(): return\n"
    "\tvar mon = team[_cursor]\n"
    "\tvar sp = MonDB.species.get(mon.get(\"species_id\",\"\"), {})\n"
    "\tvar rx = LEFT_W + 16\n"
    "\t_draw_portrait(mon, sp, rx)\n"
    "\t_draw_info(mon, sp, rx + 296)\n"
    "\t_draw_stats(mon, sp, rx + 296)\n"
    "\t_draw_moves(mon, rx, 330)\n"
    "\t_draw_desc(mon, sp, rx + 612, 330)\n"
    "\n"
    "func _draw_portrait(mon: Dictionary, sp: Dictionary, rx: int) -> void:\n"
    "\tvar pw = 280; var ph = 300\n"
    "\tvar t1 = sp.get(\"type1\",\"\u6b63\u5e38\")\n"
    "\tvar tc = TYPE_COLORS.get(t1, C_ACCENT)\n"
    "\tvar panel = _make_panel(Vector2(rx, 12), Vector2(pw, ph), C_PANEL, C_DIVIDER, 14, 1)\n"
    "\t_root.add_child(panel)\n"
    "\tvar top_bar = ColorRect.new()\n"
    "\ttop_bar.size = Vector2(pw, 5); top_bar.position = Vector2(rx, 12)\n"
    "\ttop_bar.color = tc; _root.add_child(top_bar)\n"
    "\tvar icon_path = \"res://assets/sprites/%sfront.png\" % mon.get(\"species_id\",\"\")\n"
    "\tif ResourceLoader.exists(icon_path):\n"
    "\t\tvar tex = TextureRect.new(); tex.texture = load(icon_path)\n"
    "\t\ttex.expand_mode = TextureRect.EXPAND_IGNORE_SIZE\n"
    "\t\ttex.custom_minimum_size = Vector2(210, 210); tex.size = Vector2(210, 210)\n"
    "\t\ttex.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED\n"
    "\t\ttex.position = Vector2(rx + pw/2 - 105, 28); _root.add_child(tex)\n"
    "\tvar name_lbl = Label.new()\n"
    "\tname_lbl.text = MonDB.display_name(mon)\n"
    "\tname_lbl.position = Vector2(rx + pw/2 - 36, 252)\n"
    "\tname_lbl.add_theme_font_size_override(\"font_size\", 19)\n"
    "\tname_lbl.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(name_lbl)\n"
    "\n"
    "func _draw_info(mon: Dictionary, sp: Dictionary, rx: int) -> void:\n"
    "\tvar ty = 14\n"
    "\tvar bx = rx\n"
    "\tfor tkey in [\"type1\",\"type2\"]:\n"
    "\t\tvar t = sp.get(tkey,\"\")\n"
    "\t\tif t == \"\": continue\n"
    "\t\tvar tc = TYPE_COLORS.get(t, C_ACCENT)\n"
    "\t\tvar badge = _make_panel(Vector2(bx, ty), Vector2(60, 26),\n"
    "\t\t\ttc, Color(tc.r*0.7,tc.g*0.7,tc.b*0.7,1.0), 13, 1)\n"
    "\t\t_root.add_child(badge)\n"
    "\t\tvar bl = Label.new(); bl.text = t; bl.position = Vector2(bx + 6, ty + 4)\n"
    "\t\tbl.add_theme_font_size_override(\"font_size\", 14)\n"
    "\t\tbl.add_theme_color_override(\"font_color\", Color.WHITE); _root.add_child(bl)\n"
    "\t\tbx += 68\n"
    "\tvar abilities = sp.get(\"abilities\",[])\n"
    "\tvar ability_name = abilities[0] if abilities.size() > 0 else sp.get(\"ability\",\"\u2014\")\n"
    "\tvar info_pairs = [\n"
    "\t\t[\"\u7b49\u7ea7\", \"Lv.%d\" % mon.get(\"level\",1)],\n"
    "\t\t[\"\u6027\u683c\", MonDB.natures.get(mon.get(\"nature\",\"\"),{}).get(\"name\", mon.get(\"nature\",\"\u2014\"))],\n"
    "\t\t[\"\u7279\u6027\", ability_name],\n"
    "\t]\n"
    "\tvar col_w = 110\n"
    "\tfor i in range(info_pairs.size()):\n"
    "\t\tvar kx = rx + i * col_w\n"
    "\t\tvar k = Label.new(); k.text = info_pairs[i][0]; k.position = Vector2(kx, 52)\n"
    "\t\tk.add_theme_font_size_override(\"font_size\", 11)\n"
    "\t\tk.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(k)\n"
    "\t\tvar v = Label.new(); v.text = info_pairs[i][1]; v.position = Vector2(kx, 68)\n"
    "\t\tv.add_theme_font_size_override(\"font_size\", 15)\n"
    "\t\tv.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(v)\n"
    "\n"
    "func _draw_stats(mon: Dictionary, sp: Dictionary, rx: int) -> void:\n"
    "\tvar bs = sp.get(\"base\",{})\n"
    "\tvar nd = MonDB.natures.get(mon.get(\"nature\",\"\"),{})\n"
    "\tvar nu = nd.get(\"up\",\"\"); var nd2 = nd.get(\"down\",\"\")\n"
    "\tvar nk = [\"\",\"atk\",\"def\",\"sp_atk\",\"sp_def\",\"spd\"]\n"
    "\tvar ivs = mon.get(\"ivs\",{})\n"
    "\tvar sy = 108; var rh = 31; var bw = 160; var bh = 10\n"
    "\tvar bst = 0\n"
    "\tfor i in range(6):\n"
    "\t\tvar val = bs.get(STAT_KEYS[i],0); bst += val\n"
    "\t\tvar iv_val = ivs.get(STAT_KEYS[i],0)\n"
    "\t\tvar ry = sy + i * rh\n"
    "\t\tvar nm_str = \"\"\n"
    "\t\tif i > 0 and nk[i] == nu: nm_str = \"\u2191\"\n"
    "\t\telif i > 0 and nk[i] == nd2: nm_str = \"\u2193\"\n"
    "\t\tvar col = STAT_COLORS[i]\n"
    "\t\tvar nc = C_TEXT\n"
    "\t\tif nm_str == \"\u2191\": nc = Color(0.95,0.40,0.35)\n"
    "\t\telif nm_str == \"\u2193\": nc = Color(0.40,0.60,0.95)\n"
    "\t\tvar nm = Label.new(); nm.text = STAT_NAMES[i]; nm.position = Vector2(rx, ry)\n"
    "\t\tnm.add_theme_font_size_override(\"font_size\", 13)\n"
    "\t\tnm.add_theme_color_override(\"font_color\", nc); _root.add_child(nm)\n"
    "\t\tvar vl = Label.new(); vl.text = \"%d%s\" % [val, nm_str]; vl.position = Vector2(rx + 42, ry)\n"
    "\t\tvl.add_theme_font_size_override(\"font_size\", 14)\n"
    "\t\tvl.add_theme_color_override(\"font_color\", nc); _root.add_child(vl)\n"
    "\t\tvar bg = ColorRect.new(); bg.size = Vector2(bw, bh)\n"
    "\t\tbg.position = Vector2(rx + 86, ry + 2); bg.color = Color(0.12,0.16,0.24); _root.add_child(bg)\n"
    "\t\tvar fill = ColorRect.new()\n"
    "\t\tfill.size = Vector2(bw * clampf(float(val)/255.0,0,1), bh)\n"
    "\t\tfill.position = Vector2(rx + 86, ry + 2); fill.color = col; _root.add_child(fill)\n"
    "\t\tvar iv_lbl = Label.new(); iv_lbl.text = \"IV.%d\" % iv_val\n"
    "\t\tiv_lbl.position = Vector2(rx + 252, ry)\n"
    "\t\tiv_lbl.add_theme_font_size_override(\"font_size\", 11)\n"
    "\t\tiv_lbl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(iv_lbl)\n"
    "\tvar bst_lbl = Label.new(); bst_lbl.text = \"BST  %d\" % bst\n"
    "\tbst_lbl.position = Vector2(rx, sy + 6 * rh + 2)\n"
    "\tbst_lbl.add_theme_font_size_override(\"font_size\", 12)\n"
    "\tbst_lbl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(bst_lbl)\n"
    "\n"
    "func _draw_moves(mon: Dictionary, rx: int, my: int) -> void:\n"
    "\tvar moves = mon.get(\"moves\",[])\n"
    "\tvar mw = 295; var mh = 102; var gap = 10\n"
    "\tvar t = Label.new(); t.text = \"\u6280\u80fd\"\n"
    "\tt.position = Vector2(rx, my - 22)\n"
    "\tt.add_theme_font_size_override(\"font_size\", 14)\n"
    "\tt.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(t)\n"
    "\tfor i in range(4):\n"
    "\t\tvar col_i = i % 2; var row_i = i / 2\n"
    "\t\tvar mx = rx + col_i * (mw + gap)\n"
    "\t\tvar mmy = my + row_i * (mh + gap)\n"
    "\t\tvar panel = _make_panel(Vector2(mx, mmy), Vector2(mw, mh), C_PANEL, C_DIVIDER, 10, 1)\n"
    "\t\t_root.add_child(panel)\n"
    "\t\tif i >= moves.size():\n"
    "\t\t\tvar em = Label.new(); em.text = \"\u2014 \u7a7a \u2014\"\n"
    "\t\t\tem.position = Vector2(mx + mw/2 - 22, mmy + mh/2 - 10)\n"
    "\t\t\tem.add_theme_font_size_override(\"font_size\", 14)\n"
    "\t\t\tem.add_theme_color_override(\"font_color\", C_DIVIDER); _root.add_child(em); continue\n"
    "\t\tvar mv = MonDB.moves.get(moves[i],{})\n"
    "\t\tvar mt = mv.get(\"type\",\"\u6b63\u5e38\")\n"
    "\t\tvar tc = TYPE_COLORS.get(mt, C_ACCENT)\n"
    "\t\tvar stripe = ColorRect.new()\n"
    "\t\tstripe.size = Vector2(5, mh); stripe.position = Vector2(mx, mmy)\n"
    "\t\tstripe.color = tc; _root.add_child(stripe)\n"
    "\t\tvar nl = Label.new(); nl.text = mv.get(\"name\", moves[i])\n"
    "\t\tnl.position = Vector2(mx + 14, mmy + 10)\n"
    "\t\tnl.add_theme_font_size_override(\"font_size\", 16)\n"
    "\t\tnl.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(nl)\n"
    "\t\tvar bb = ColorRect.new()\n"
    "\t\tbb.size = Vector2(44, 20); bb.position = Vector2(mx + mw - 52, mmy + 9)\n"
    "\t\tbb.color = tc; _root.add_child(bb)\n"
    "\t\tvar bt = Label.new(); bt.text = mt; bt.position = Vector2(mx + mw - 50, mmy + 10)\n"
    "\t\tbt.add_theme_font_size_override(\"font_size\", 11)\n"
    "\t\tbt.add_theme_color_override(\"font_color\", Color.WHITE); _root.add_child(bt)\n"
    "\t\tvar pow_str = str(mv.get(\"power\",0)) if mv.get(\"power\",0) > 0 else \"\u2014\"\n"
    "\t\tvar acc_str = str(mv.get(\"accuracy\",100)) if mv.get(\"accuracy\",0) > 0 else \"\u2014\"\n"
    "\t\tvar pl = Label.new(); pl.text = \"\u5a01\u529b%s  \u547d\u4e2d%s\" % [pow_str, acc_str]\n"
    "\t\tpl.position = Vector2(mx + 14, mmy + 36)\n"
    "\t\tpl.add_theme_font_size_override(\"font_size\", 13)\n"
    "\t\tpl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(pl)\n"
    "\t\tvar pp = mv.get(\"pp\",0)\n"
    "\t\tvar pp_lbl = Label.new(); pp_lbl.text = \"PP  %d / %d\" % [pp, pp]\n"
    "\t\tpp_lbl.position = Vector2(mx + 14, mmy + 56)\n"
    "\t\tpp_lbl.add_theme_font_size_override(\"font_size\", 13)\n"
    "\t\tpp_lbl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(pp_lbl)\n"
    "\t\tvar cat = mv.get(\"category\",\"\u7269\u7406\")\n"
    "\t\tvar cat_col = Color(0.92,0.42,0.28) if cat==\"\u7269\u7406\" else Color(0.42,0.55,0.90) if cat==\"\u7279\u6b8a\" else Color(0.60,0.60,0.60)\n"
    "\t\tvar cl = Label.new(); cl.text = cat; cl.position = Vector2(mx + 14, mmy + 76)\n"
    "\t\tcl.add_theme_font_size_override(\"font_size\", 12)\n"
    "\t\tcl.add_theme_color_override(\"font_color\", cat_col); _root.add_child(cl)\n"
    "\n"
    "func _draw_desc(mon: Dictionary, sp: Dictionary, rx: int, my: int) -> void:\n"
    "\tvar pw = VW - rx - 14; var ph = 214\n"
    "\tvar panel = _make_panel(Vector2(rx, my), Vector2(pw, ph), C_PANEL, C_DIVIDER, 10, 1)\n"
    "\t_root.add_child(panel)\n"
    "\tvar desc = sp.get(\"description\",\"\")\n"
    "\tif desc != \"\":\n"
    "\t\tvar dl = Label.new(); dl.text = desc\n"
    "\t\tdl.position = Vector2(rx + 12, my + 12); dl.size = Vector2(pw - 24, 120)\n"
    "\t\tdl.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART\n"
    "\t\tdl.add_theme_font_size_override(\"font_size\", 13)\n"
    "\t\tdl.add_theme_color_override(\"font_color\", C_TEXT); _root.add_child(dl)\n"
    "\tvar h = sp.get(\"height\",0.0); var w = sp.get(\"weight\",0.0)\n"
    "\tif h > 0 or w > 0:\n"
    "\t\tvar hw = Label.new(); hw.text = \"\u8eab\u9ad8 %.1fm   \u4f53\u91cd %.1fkg\" % [h, w]\n"
    "\t\thw.position = Vector2(rx + 12, my + 152)\n"
    "\t\thw.add_theme_font_size_override(\"font_size\", 13)\n"
    "\t\thw.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(hw)\n"
    "\tvar met_date = mon.get(\"met_date\",\"\"); var met_loc = mon.get(\"met_location\",\"\")\n"
    "\tif met_date != \"\" or met_loc != \"\":\n"
    "\t\tvar met = Label.new()\n"
    "\t\tmet.text = (\"%s  \u5728\u300c%s\u300d\u76f8\u9047\" % [met_date, met_loc]) if met_date != \"\" else (\"\u5728\u300c%s\u300d\u76f8\u9047\" % met_loc)\n"
    "\t\tmet.position = Vector2(rx + 12, my + 180)\n"
    "\t\tmet.add_theme_font_size_override(\"font_size\", 12)\n"
    "\t\tmet.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(met)\n"
    "\n"
    "func _draw_actions() -> void:\n"
    "\tvar bw = 130; var bh = 44; var gap = 16\n"
    "\tvar total_w = 3 * bw + 2 * gap\n"
    "\tvar bx = VW/2 - total_w/2; var by = VH - bh - 12\n"
    "\tfor i in range(ACTIONS.size()):\n"
    "\t\tvar sel = (_focus == \"actions\" and _action_cursor == i)\n"
    "\t\tvar bxi = bx + i * (bw + gap)\n"
    "\t\tvar btn = _make_panel(Vector2(bxi, by), Vector2(bw, bh),\n"
    "\t\t\tC_ACCENT if sel else C_PANEL,\n"
    "\t\t\tC_SEL_BORDER if sel else C_DIVIDER, 10, 2 if sel else 1)\n"
    "\t\t_root.add_child(btn)\n"
    "\t\tvar lbl = Label.new(); lbl.text = ACTIONS[i]\n"
    "\t\tlbl.position = Vector2(bxi + bw/2 - 20, by + 10)\n"
    "\t\tlbl.add_theme_font_size_override(\"font_size\", 17)\n"
    "\t\tlbl.add_theme_color_override(\"font_color\", Color.WHITE if sel else C_TEXT)\n"
    "\t\t_root.add_child(lbl)\n"
    "\n"
    "func _draw_close_btn() -> void:\n"
    "\tvar cl = Label.new(); cl.text = \"\u2715  [Esc]\"\n"
    "\tcl.position = Vector2(VW - 84, 16)\n"
    "\tcl.add_theme_font_size_override(\"font_size\", 14)\n"
    "\tcl.add_theme_color_override(\"font_color\", C_SUB); _root.add_child(cl)\n"
    "\n"
    "func _make_panel(pos: Vector2, size: Vector2, bg: Color, border: Color, radius: int, bw: int) -> PanelContainer:\n"
    "\tvar p = PanelContainer.new()\n"
    "\tp.position = pos; p.custom_minimum_size = size; p.size = size\n"
    "\tvar s = StyleBoxFlat.new(); s.bg_color = bg\n"
    "\ts.corner_radius_top_left = radius; s.corner_radius_top_right = radius\n"
    "\ts.corner_radius_bottom_left = radius; s.corner_radius_bottom_right = radius\n"
    "\ts.border_color = border\n"
    "\ts.border_width_left = bw; s.border_width_right = bw\n"
    "\ts.border_width_top = bw; s.border_width_bottom = bw\n"
    "\tp.add_theme_stylebox_override(\"panel\", s); return p\n"
    "\n"
    "func _input(event: InputEvent) -> void:\n"
    "\tif event.is_action_pressed(\"ui_cancel\"):\n"
    "\t\tget_viewport().set_input_as_handled()\n"
    "\t\tclosed.emit(); queue_free(); return\n"
    "\tif _focus == \"party\":\n"
    "\t\tif event.is_action_pressed(\"ui_down\"):\n"
    "\t\t\t_cursor = (_cursor + 1) % max(GameState.player_team.size(), 1)\n"
    "\t\t\tget_viewport().set_input_as_handled(); _render()\n"
    "\t\telif event.is_action_pressed(\"ui_up\"):\n"
    "\t\t\t_cursor = (_cursor - 1 + max(GameState.player_team.size(),1)) % max(GameState.player_team.size(),1)\n"
    "\t\t\tget_viewport().set_input_as_handled(); _render()\n"
    "\t\telif event.is_action_pressed(\"ui_accept\"):\n"
    "\t\t\t_focus = \"actions\"; get_viewport().set_input_as_handled(); _render()\n"
    "\telif _focus == \"actions\":\n"
    "\t\tif event.is_action_pressed(\"ui_left\"):\n"
    "\t\t\t_action_cursor = (_action_cursor - 1 + ACTIONS.size()) % ACTIONS.size()\n"
    "\t\t\tget_viewport().set_input_as_handled(); _render()\n"
    "\t\telif event.is_action_pressed(\"ui_right\"):\n"
    "\t\t\t_action_cursor = (_action_cursor + 1) % ACTIONS.size()\n"
    "\t\t\tget_viewport().set_input_as_handled(); _render()\n"
    "\t\telif event.is_action_pressed(\"ui_cancel\"):\n"
    "\t\t\t_focus = \"party\"; get_viewport().set_input_as_handled(); _render()\n"
    "\t\telif event.is_action_pressed(\"ui_accept\"):\n"
    "\t\t\tif _action_cursor == 2:\n"
    "\t\t\t\tclosed.emit(); queue_free()\n"
    "\t\t\tget_viewport().set_input_as_handled()\n"
)

path = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'ui', 'party_ui.gd')
with open(path, 'w', encoding='utf-8') as f:
    f.write(code)
print('Done', len(code), 'chars written to', path)
